apply plugin: 'com.android.application'

android {
    namespace 'com.example.subtitlefixer'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.subtitlefixer"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}